content/en/docs/how-tos/_index.md
content/en/docs/how-tos/hetzner.md

As part of https://github.com/aenix-io/cozystack/issues/79

Document Hetzner installation

---

content/en/docs/bundles/_index.md
content/en/docs/bundles/distro-full.md
content/en/docs/bundles/distro-hosted.md
content/en/docs/bundles/paas-full.md
content/en/docs/bundles/paas-hosted.md
content/en/docs/concepts.md
content/en/docs/faq.md
content/en/docs/get-started.md

fixes https://github.com/aenix-io/cozystack-website/issues/8

Add basic doc for bundles

---

content/en/docs/get-started.md

link https://github.com/aenix-io/cozystack/pull/97

Preapare release v0.3.1

---

content/en/docs/how-tos/hetzner.md

Signed-off-by: Andrei Kvapil <kvapss@gmail.com>

Use latest image for hetzner how-to

---

content/en/docs/faq.md

- FAQ: enable dashboard access via nginx-ingress
- How to cleanup etcd state
- Document how to generate kubeconfig for tenant
fixes https://github.com/aenix-io/cozystack/issues/84, https://github.com/aenix-io/cozystack/issues/120, https://github.com/aenix-io/cozystack/issues/37

upd docs operaton

---

content/en/docs/talos/configuration/talos-bootstrap.md

As part of https://github.com/aenix-io/cozystack/issues/141
Signed-off-by: Andrei Kvapil <kvapss@gmail.com>

Specify cozy.local as cluster domain

---

content/en/docs/talos/installation/pxe.md

Changed IPs in examples to reflect other parts of docs and pictures.

example configs change

---

content/en/docs/get-started.md
content/en/docs/talos/installation/hetzner.md
content/en/docs/talos/installation/pxe.md

- Upd hetzner instruction
- release-v0.10.3

release 0.10.3

---

content/en/docs/get-started.md
content/en/docs/talos/configuration/talos-bootstrap.md
content/en/docs/talos/installation/pxe.md

Signed-off-by: Andrei Kvapil <kvapss@gmail.com>

Prepare release v0.16

---

content/en/docs/get-started.md
content/en/docs/talos/installation/pxe.md

Signed-off-by: Andrei Kvapil <kvapss@gmail.com>

Prepare release v0.22.0

---

content/en/docs/roadmap.html

Roadmap in SVG pic added on website page

Update roadmap.html added pic of roadmap

---

content/en/docs/operations/storage/dedicated-network.md

Removed reference to a document that's not merged yet

[docs] Dedicated Network for LINSTOR: fixup

---

content/en/docs/getting-started/first-deployment.md

It helps people do steps one-by-one, without skipping them.

[docs] Deploy Cozystack: make steps numbered

---

content/en/docs/guides/bundles/_index.md

[docs] Explain bundles: comparison table

---

content/en/docs/getting-started/first-deployment.md
content/en/docs/operations/bundles/_index.md
content/en/docs/operations/faq.md

Move FAQ from guides to operations as well
Part of #110

[docs] Move bundles operations reference to the bundles page

---

content/en/docs/guides/bundles/_index.md

Update bundles table

---

content/en/docs/guides/bundles/_index.md

Using a link to code on GitHub until we have a proper list of supported operators in the docs. >>> #195

[docs] Bundles: add link to k8s operators list

---

content/en/docs/operations/talos/configuration/talm.md

There's still work to do, and Oracle Cloud guide explains using Talm in more detail.

[docs] Proofread the Talm installation guide

---

content/en/docs/operations/faq.md

Add method to reset `etcd` using `talm`

[FAQ] reset etcd

---

content/en/docs/operations/storage/nfs.md

Source: cozystack/cozystack#1133

[docs] Add NFS driver documentation

---

content/en/docs/getting-started/install-cozystack.md

Replacement PR for https://github.com/cozystack/website/pull/261, where I can't rebase branches before merging.
Resolves #261

[docs] Add instructions for restoring ZFS/LVM storage-pool on nodes after reset
